template_path: managed_policy_attachable_role.template
parameters:
  Name: apigateway_admin_analytics_get_role
  ManagedPolicyArns:
    - !stack_output iam/policies/apigateway-admin-analytics-get-policy/policy.yaml::PolicyArn
  Services:
    - apigateway.amazonaws.com
