# APIGateway assumes this role to invoke the lambda.
template_path: managed_policy_attachable_role.template
parameters:
  Name: apigateway_s3_visited_resources_post_role
  ManagedPolicyArns:
    - !stack_output iam/policies/apigateway-s3-visited-resources-post/policy.yaml::PolicyArn
  Services:
    - apigateway.amazonaws.com
