template_path: iam_managed_policy.j2

sceptre_user_data:
  PolicyDocument: !file config/iam/policies/apigateway-admin-analytics-get-policy/policy.json

parameters:
  Name: apigateway-admin-analytics-get-policy
