version=0.1
[default.global.parameters]
stack_name = "moralpain-api"

[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mg5hrwidlmdq"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_prefix = "moralpain-api"
image_repositories = []
