AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  moralpain

  SAM Template for moralpain

Parameters:
  Prefix:
    Description: unique identifier for resources
    Type: String
    Default: ''

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: v1
      DefinitionUri: api.yaml

  SubmitSurveyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Prefix}SubmitSurvey
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.UniqueKeyUploader::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          bucket: moralpain-submissions
          prefix: surveys
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_submit_survey_role

  SubmitVisitedResiliencyResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Prefix}SubmitVisitedResiliencyResources
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.UniqueKeyUploader::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          bucket: moralpain-submissions
          prefix: resiliency
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_submit_visited_resources_role

  FetchSubmissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Prefix}FetchSubmissions
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.SubmissionFetcher::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          bucket: moralpain-submissions
          prefix: surveys
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_fetch_submissions_role
      Timeout: 60
  
  AnalyzeSubmissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Prefix}AnalyzeSubmissions
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.SubmissionAnalyzer::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          bucket: moralpain-submissions
          prefix: surveys
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_analyze_submissions_role
  
  FetchSubmissionFieldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Prefix}FetchSubmissionField
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.SubmissionFieldFetcher::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          bucket: moralpain-submissions
          prefix: surveys
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_fetch_submission_field_role
      Timeout: 60

  SubmitSubmissionFieldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${Prefix}SubmitSubmissionField
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.SubmissionUpdater::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          bucket: moralpain-submissions
          prefix: single
          uploadFileName: submission.json
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_submit_submission_field_role


Outputs:
  APIUri:
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com"
  SubimitSurveyFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for SubmitSurvey function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/survey/"
  SubmitSurveyFunction:
    Description: "SubmitSurvey Lambda Function ARN"
    Value: !GetAtt SubmitSurveyFunction.Arn
  SubmitVisitedResiliencyResourcesFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for SubmitVisitedResiliencyResources function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/resiliency/"
  SubmitVisitedResiliencyResourcesFunction:
    Description: "SubmitVisitedResiliencyResources Lambda Function ARN"
    Value: !GetAtt SubmitVisitedResiliencyResourcesFunction.Arn
  FetchSubmissionsFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for FetchSubmissions function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/admin/submissions/"
  FetchSubmissionsFunction:
    Description: "FetchSubmissions Lambda Function ARN"
    Value: !GetAtt FetchSubmissionsFunction.Arn
