template_path: iam_managed_policy.j2

sceptre_user_data:
  PolicyDocument: !file config/iam/policies/lambda-submit-visited-resources-policy/policy.json

parameters:
  Name: lambda_submit_visited_resources_policy
