name: Publish docs to S3.

on:
  push:
    branches: 
        - backend_api

jobs:
  docs:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print workspace path
        run: |
          echo $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
      - name: redoc-cli 
        uses: seeebiii/redoc-cli-github-action@v9
        with:
          args: >
            build infrastructure/sam/api.yaml 
            --options docs/redoc.json
            --output ${GITHUB_WORKSPACE}/index.html
      - name: Print workspace path 2
        run: |
          echo $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
      - name: Upload S3
        uses: nicholasphair/upload-s3-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_PUBLIC_BUCKET }}
          destination_dir: 'docs/'
          source_dir: index.html
